name: CI/CD

on:
  push:
  pull_request:
  # Run daily at 0:01 UTC
  schedule:
  - cron:  '1 0 * * *'

jobs:
  test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install --ignore-installed -U -q --no-cache-dir -e .[test]
        python -m pip install cython
        python -m pip install --upgrade --no-cache-dir git+git://github.com/scikit-hep/iminuit.git@31799ac188798ad8166375cc4c3a0cfcb2825995
        python -m pip list
    - name: Test with pytest
      run: |
        python -m pytest -r sx tests/test_optim.py
        # python -m pytest -r sx --ignore tests/benchmarks/ --ignore tests/contrib --ignore tests/test_notebooks.py
    - name: Report coverage with Codecov
      if: github.event_name == 'push' && matrix.python-version == 3.7 && matrix.os == 'ubuntu-latest'
      uses: codecov/codecov-action@v1.0.5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests
    - name: Test Contrib module with pytest
      run: |
        python -m pytest -r sx tests/contrib --mpl --mpl-baseline-path tests/contrib/baseline
    - name: Run benchmarks
      if: github.event_name == 'schedule' && matrix.python-version == 3.7
      run: |
        python -m pytest -r sx --benchmark-sort=mean tests/benchmarks/test_benchmark.py
